[package]
name = "radicle-cli"
description = "Radicle command line interface"
version = "0.5.1"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
rust-version = "1.59"

[features]
default = ["ethereum"]
ethereum = ["rad-ens", "rad-account", "rad-help/ethereum", "rad-gov", "ethers", "tokio", "futures"]

[package.metadata.deb]
assets = [
    ["target/release/rad-self", "usr/bin/rad-self", "755"],
    ["target/release/rad-inspect", "usr/bin/rad-inspect", "755"],
    ["target/release/rad-account", "usr/bin/rad-account", "755"],
    ["target/release/rad-sync", "usr/bin/rad-sync", "755"],
    ["target/release/rad-help", "usr/bin/rad-help", "755"],
    ["target/release/rad-ens", "usr/bin/rad-ens", "755"],
    ["target/release/rad-push", "usr/bin/rad-push", "755"],
    ["target/release/rad", "usr/bin/rad", "755"],
    ["target/release/rad-auth", "usr/bin/rad-auth", "755"],
    ["target/release/rad-rm", "usr/bin/rad-rm", "755"],
    ["target/release/rad-track", "usr/bin/rad-track", "755"],
    ["target/release/rad-ls", "usr/bin/rad-ls", "755"],
    ["target/release/rad-mycommand", "usr/bin/rad-mycommand", "755"],
    ["target/release/rad-init", "usr/bin/rad-init", "755"],
    ["target/release/rad-clone", "usr/bin/rad-clone", "755"],
    ["target/release/rad-pull", "usr/bin/rad-pull", "755"],
    ["target/release/rad-checkout", "usr/bin/rad-checkout", "755"],
    ["target/release/rad-untrack", "usr/bin/rad-untrack", "755"],
    ["target/release/rad-remote", "usr/bin/rad-remote", "755"],
    ["target/release/rad-gov", "usr/bin/rad-gov", "755"],
    ["target/release/git-remote-rad", "usr/bin/git-remote-rad", "755"],
    ["rad.1.gz", "usr/share/man/man1/rad.1.gz", "644"],
    ["rad-checkout.1.gz", "usr/share/man/man1/rad-checkout.1.gz", "644"],
    ["rad-sync.1.gz", "usr/share/man/man1/rad-sync.1.gz", "644"]
]

[dependencies]
anyhow = "1.0"
lexopt = "0.2"
colored = { version = "1.9" }
atty = { version = "0.2" }
log = { version = "0.4", features = ["std"] }
librad = { version = "0" }
futures-lite = { version = "1.12" }
rad = { path = "./rad" }
lnk-profile = { version = "0" }
rad-clone = { path = "./clone" }
rad-auth = { path = "./auth" }
rad-common = { path = "./common" }
rad-terminal = { path = "./terminal" }
rad-init = { path = "./init" }
rad-self = { path = "./self" }
rad-inspect = { path = "./inspect" }
rad-push = { path = "./push" }
rad-pull = { path = "./pull" }
rad-sync = { path = "./sync" }
rad-remote = { path = "./remote" }
rad-checkout = { path = "./checkout" }
rad-track = { path = "./track" }
rad-untrack = { path = "./untrack" }
rad-help = { path = "./help" }
rad-ls = { path = "./ls" }
rad-rm = { path = "./rm" }
link-identities = { version = "0" }
radicle-git-helpers = { version = "0" }
url = { version = "2" }

# Ethereum functionality

ethers = { version = "0.6.2", optional = true }
rad-account = { path = "./account", optional = true }
rad-ens = { path = "./ens", optional = true }
rad-gov = { path = "./gov", optional = true }
tokio = { version = "1.10", features = ["rt"], optional = true }
futures = { version = "0.3", optional = true }

[dev-dependencies]
assay = "0.1.1"
assert_cmd = "2.0"

[[bin]]
name = "rad-account"
required-features = ["ethereum"]

[[bin]]
name = "rad-ens"
required-features = ["ethereum"]

[[bin]]
name = "rad-gov"
required-features = ["ethereum"]

[workspace]
members = [
  "anchor",
  "account",
  "terminal",
  "common",
  "checkout",
  "ens",
  "auth",
  "help",
  "rad",
  "init",
  "ls",
  "rm",
  "push",
  "pull",
  "remote",
  "sync",
  "self",
  "inspect",
  "track",
  "untrack",
  "gov"
]

[patch.crates-io.link-crypto]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-03-01"

[patch.crates-io.link-identities]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-03-01"

[patch.crates-io.radicle-git-helpers]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-03-01"

[patch.crates-io.librad]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-03-01"

[patch.crates-io.lnk-clib]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-03-01"

[patch.crates-io.lnk-profile]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-03-01"

[patch.crates-io.radicle-git-ext]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-03-01"

[patch.crates-io.lnk-identities]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-03-01"

[patch.crates-io.thrussh-encoding]
git = "https://github.com/FintanH/thrussh.git"
branch = "generic-agent"
